package com.vaadin.cdi.test.helloWorld;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Layout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class Sample extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Sample() {
		setCompositionRoot(buildMainLayout());
	}

	@AutoGenerated
	private Layout buildMainLayout() {

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		return buildVerticalLayout_1();
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(true);
		verticalLayout_1.setSpacing(true);

		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		verticalLayout_1.addComponent(verticalLayout_2);
		verticalLayout_1.setExpandRatio(verticalLayout_2, 1.0f);
		verticalLayout_1.setComponentAlignment(verticalLayout_2, new Alignment(
				9));

		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		verticalLayout_1.addComponent(verticalLayout_3);
		verticalLayout_1.setComponentAlignment(verticalLayout_3, new Alignment(
				9));

		return verticalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		// verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);
		verticalLayout_2.setSpacing(false);

		VerticalLayout dummy = new VerticalLayout();
		verticalLayout_2.addComponent(dummy);
		dummy.setHeight("100%");

		for (int i = 0; i < 50; i++) {
			Label label_5 = new Label();
			label_5.setImmediate(false);
			label_5.setValue("Hello");
			verticalLayout_2.addComponent(label_5);
			verticalLayout_2.setComponentAlignment(label_5,
					Alignment.BOTTOM_LEFT);
		}


		return verticalLayout_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("-1px");
		verticalLayout_3.setMargin(false);

		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("100.0%");
		textField_1.setHeight("-1px");
		verticalLayout_3.addComponent(textField_1);

		// button_1
		button_1 = new Button();
		button_1.setCaption("Absenden");
		button_1.setImmediate(true);
		button_1.setWidth("100.0%");
		button_1.setHeight("-1px");
		verticalLayout_3.addComponent(button_1);

		return verticalLayout_3;
	}

}
